// Code generated by smithy-go-codegen DO NOT EDIT.

package types

import (
	"fmt"
	smithy "github.com/awslabs/smithy-go"
	"github.com/awslabs/smithy-go/ptr"
)

// Request validation failed, there is no usable message in the context, or the bot
// build failed, is still in progress, or contains unbuilt changes.
type BadRequestException struct {
	Message *string
}

func (e *BadRequestException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *BadRequestException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *BadRequestException) ErrorCode() string             { return "BadRequestException" }
func (e *BadRequestException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (e *BadRequestException) GetMessage() string {
	return ptr.ToString(e.Message)
}
func (e *BadRequestException) HasMessage() bool {
	return e.Message != nil
}

// Two clients are using the same AWS account, Amazon Lex bot, and user ID.
type ConflictException struct {
	Message *string
}

func (e *ConflictException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *ConflictException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *ConflictException) ErrorCode() string             { return "ConflictException" }
func (e *ConflictException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (e *ConflictException) GetMessage() string {
	return ptr.ToString(e.Message)
}
func (e *ConflictException) HasMessage() bool {
	return e.Message != nil
}

// Internal service error. Retry the call.
type InternalFailureException struct {
	Message *string
}

func (e *InternalFailureException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *InternalFailureException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *InternalFailureException) ErrorCode() string             { return "InternalFailureException" }
func (e *InternalFailureException) ErrorFault() smithy.ErrorFault { return smithy.FaultServer }
func (e *InternalFailureException) GetMessage() string {
	return ptr.ToString(e.Message)
}
func (e *InternalFailureException) HasMessage() bool {
	return e.Message != nil
}

// Exceeded a limit.
type LimitExceededException struct {
	Message *string

	RetryAfterSeconds *string
}

func (e *LimitExceededException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *LimitExceededException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *LimitExceededException) ErrorCode() string             { return "LimitExceededException" }
func (e *LimitExceededException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (e *LimitExceededException) GetMessage() string {
	return ptr.ToString(e.Message)
}
func (e *LimitExceededException) HasMessage() bool {
	return e.Message != nil
}
func (e *LimitExceededException) GetRetryAfterSeconds() string {
	return ptr.ToString(e.RetryAfterSeconds)
}
func (e *LimitExceededException) HasRetryAfterSeconds() bool {
	return e.RetryAfterSeconds != nil
}

// The accept header in the request does not have a valid value.
type NotAcceptableException struct {
	Message *string
}

func (e *NotAcceptableException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *NotAcceptableException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *NotAcceptableException) ErrorCode() string             { return "NotAcceptableException" }
func (e *NotAcceptableException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (e *NotAcceptableException) GetMessage() string {
	return ptr.ToString(e.Message)
}
func (e *NotAcceptableException) HasMessage() bool {
	return e.Message != nil
}

// The resource (such as the Amazon Lex bot or an alias) that is referred to is not
// found.
type NotFoundException struct {
	Message *string
}

func (e *NotFoundException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *NotFoundException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *NotFoundException) ErrorCode() string             { return "NotFoundException" }
func (e *NotFoundException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (e *NotFoundException) GetMessage() string {
	return ptr.ToString(e.Message)
}
func (e *NotFoundException) HasMessage() bool {
	return e.Message != nil
}

// The input speech is too long.
type RequestTimeoutException struct {
	Message *string
}

func (e *RequestTimeoutException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *RequestTimeoutException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *RequestTimeoutException) ErrorCode() string             { return "RequestTimeoutException" }
func (e *RequestTimeoutException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (e *RequestTimeoutException) GetMessage() string {
	return ptr.ToString(e.Message)
}
func (e *RequestTimeoutException) HasMessage() bool {
	return e.Message != nil
}

// The Content-Type header (PostContent API) has an invalid value.
type UnsupportedMediaTypeException struct {
	Message *string
}

func (e *UnsupportedMediaTypeException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *UnsupportedMediaTypeException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *UnsupportedMediaTypeException) ErrorCode() string             { return "UnsupportedMediaTypeException" }
func (e *UnsupportedMediaTypeException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (e *UnsupportedMediaTypeException) GetMessage() string {
	return ptr.ToString(e.Message)
}
func (e *UnsupportedMediaTypeException) HasMessage() bool {
	return e.Message != nil
}

// Either the Amazon Lex bot is still building, or one of the dependent services
// (Amazon Polly, AWS Lambda) failed with an internal service error.
type BadGatewayException struct {
	Message *string
}

func (e *BadGatewayException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *BadGatewayException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *BadGatewayException) ErrorCode() string             { return "BadGatewayException" }
func (e *BadGatewayException) ErrorFault() smithy.ErrorFault { return smithy.FaultServer }
func (e *BadGatewayException) GetMessage() string {
	return ptr.ToString(e.Message)
}
func (e *BadGatewayException) HasMessage() bool {
	return e.Message != nil
}

// One of the dependencies, such as AWS Lambda or Amazon Polly, threw an exception.
// For example,
//
//     * If Amazon Lex does not have sufficient permissions to call a
// Lambda function.
//
//     * If a Lambda function takes longer than 30 seconds to
// execute.
//
//     * If a fulfillment Lambda function returns a Delegate dialog
// action without removing any slot values.
type DependencyFailedException struct {
	Message *string
}

func (e *DependencyFailedException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *DependencyFailedException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *DependencyFailedException) ErrorCode() string             { return "DependencyFailedException" }
func (e *DependencyFailedException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
func (e *DependencyFailedException) GetMessage() string {
	return ptr.ToString(e.Message)
}
func (e *DependencyFailedException) HasMessage() bool {
	return e.Message != nil
}

// This exception is not used.
type LoopDetectedException struct {
	Message *string
}

func (e *LoopDetectedException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *LoopDetectedException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *LoopDetectedException) ErrorCode() string             { return "LoopDetectedException" }
func (e *LoopDetectedException) ErrorFault() smithy.ErrorFault { return smithy.FaultServer }
func (e *LoopDetectedException) GetMessage() string {
	return ptr.ToString(e.Message)
}
func (e *LoopDetectedException) HasMessage() bool {
	return e.Message != nil
}
